language: ruby
os: linux
dist: xenial

rvm:
  - 2.4
  - 2.5
  - 2.6
  - 2.7
  - ruby-head

bundler_args: --without development --jobs=3 --retry=3

jobs:
  allow_failures:
    - rvm: ruby-head
  fast_finish: true
